name: build and test environment
on:
  workflow_dispatch:
env:
  NODE_VERSION: "18.x"

jobs:
  install-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          cache-dependency-path: subdir/package-lock.json

      - name: Run tests
        run: |
          npm ci
          npm run build --if-present
          npm test

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploy to staging"

  prod_deploy:
    runs-on: ubuntu-latest
    needs: stage_deploy
    environment:
      name: staging

    steps:
      - name: Deploy to Production
        run: |
          echo "Production to staging"
